obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.18, -0.2], [-0.18, 0.2], [0.18, 0.2], [0.18, -0.2]]
#robot_radius: ir_of_robot
inflation_radius: 0.6

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
